require("blocks/production/insulator-weaver")
require("blocks/production/rock-crusher")
require("blocks/production/sulfur-extractor")
require("blocks/production/heavy-oil-processor")
require("blocks/production/light-oil-processor")