//blocks-production
require("blocks/production/mineral-extractor")
require("blocks/production/rock-crusher")
require("blocks/production/heavy-oil-processor")
require("blocks/production/light-oil-processor")
//blocks-distribution
require("blocks/distribution/omni-bridge-conveyor")
//blocks-liquid
require("blocks/liquid/omni-bridge-conduit")
//blocks-drills
require("blocks/drills/bowels-mining-station")
//blocks-walls
require("blocks/walls/naquada-wall")
require("blocks/walls/naquada-wall-large")